DROP TABLE OUVRAGE CASCADE CONSTRAINTS;
DROP TABLE EXEMPLAIRE CASCADE CONSTRAINTS;
DROP TABLE MEMBRE CASCADE CONSTRAINTS;
DROP TABLE EMPRUNTS CASCADE CONSTRAINTS;
DROP TABLE GENRE CASCADE CONSTRAINTS;
DROP TABLE DETAILS CASCADE CONSTRAINTS;
DROP SYNONYM ABONNES;
DROP SEQUENCE uniq_ID_membre;
DROP SEQUENCE uniq_ID_emprunt;
-- Delte datas from recycle bin
PURGE TABLE OUVRAGE;
PURGE TABLE EXEMPLAIRE;
PURGE TABLE MEMBRE;
PURGE TABLE EMPRUNTS;
PURGE TABLE GENRE;
PURGE TABLE DETAILS;
