DROP TABLE OUVRAGE CASCADE CONSTRAINTS;
DROP TABLE EXEMPLAIRE CASCADE CONSTRAINTS;
DROP TABLE MEMBRE CASCADE CONSTRAINTS;
DROP TABLE EMPRUNTS CASCADE CONSTRAINTS;
DROP TABLE GENRE CASCADE CONSTRAINTS;
DROP TABLE DETAILS CASCADE CONSTRAINTS;
DROP SYNONYM ABONNES;
