DROP TABLE Ouvrage CASCADE CONSTRAINTS;
DROP TABLE Exemplaire CASCADE CONSTRAINTS;
DROP TABLE Membre CASCADE CONSTRAINTS;
DROP TABLE Emprunts CASCADE CONSTRAINTS;
DROP TABLE Genre CASCADE CONSTRAINTS;
DROP TABLE Details CASCADE CONSTRAINTS;
DROP SYNONYM Abonnes;
DROP SEQUENCE Uniq_id_membre;
DROP SEQUENCE Uniq_id_emprunt;
-- Delte datas from recycle bin
Purge TABLE Ouvrage;
Purge TABLE Exemplaire;
Purge TABLE Membre;
Purge TABLE Emprunts;
Purge TABLE Genre;
Purge TABLE Details;
